import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/pages/NavBar";
import Footer from "@/components/pages/Footer";
import TargetCursor from "@/components/TargetCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        {/* Target Cursor */}
        <TargetCursor 
          targetSelector=".cursor-target"
          spinDuration={0}
          hideDefaultCursor={true}
        />
        <NavBar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
